import {
  Home, Flame, TreePine, Wind, Waves, Sparkles, MapPin, Play, RotateCcw,
  ArrowLeft, Loader2, Globe, Languages, Mountain, Castle, Sword, Shield,
  Star, Sun, Moon, Cloud, Zap, Heart, Eye, Diamond, Gem, Crown,
  Key, Lock, Footprints, Compass, Telescope, BookOpen, Scroll,
  Feather, Wand2, Rabbit, Fish, Bird, Bug, Flower, Leaf, Snowflake,
  Navigation, Route, Signpost, Milestone, Target, Locate,
  Flower2, Cherry, CloudSnow, CloudRain, Rainbow, Sunrise, Sunset, Eclipse,
  Snail, Turtle, Cat, Dog, MousePointer, PawPrint,
  Shell, Axe, Hammer, Bolt, Power,
  Building, Church, House, Warehouse, Factory, Tent, DoorOpen, DoorClosed,
  Unlock, Box, Package, Gift, Coins,
  Wrench, Pickaxe, Shovel, Anchor, Bell,
  HeartHandshake, Smile, Frown, Angry,
  Book, ScrollText, Map,
  Watch, Clock, Timer, Hourglass, Calendar,
  Music, Drum, Guitar, Piano,
  Pill, Syringe, Bandage, Hospital,
  Microscope, Beaker, Atom, Magnet, Scale, Ruler, Calculator,
} from 'lucide-react';

export const APP_ICON_MAP: { [key: string]: React.ComponentType<React.SVGProps<SVGSVGElement>> } = {
  Home, Flame, TreePine, Wind, Waves, Sparkles, MapPin, Play, RotateCcw,
  ArrowLeft, Loader2, Globe, Languages, Mountain, Castle, Sword, Shield,
  Star, Sun, Moon, Cloud, Zap, Heart, Eye, Diamond, Gem, Crown,
  Key, Lock, Footprints, Compass, Telescope, BookOpen, Scroll,
  Feather, Wand2, Rabbit, Fish, Bird, Bug, Flower, Leaf, Snowflake,
  Navigation, Route, Signpost, Milestone, Target, Locate,
  Flower2, Cherry, CloudSnow, CloudRain, Rainbow, Sunrise, Sunset, Eclipse,
  Snail, Turtle, Cat, Dog, MousePointer, PawPrint,
  Shell, Axe, Hammer, Bolt, Power,
  Building, Church, House, Warehouse, Factory, Tent, DoorOpen, DoorClosed,
  Unlock, Box, Package, Gift, Coins,
  Wrench, Pickaxe, Shovel, Anchor, Bell,
  HeartHandshake, Smile, Frown, Angry,
  Book, ScrollText, Map,
  Watch, Clock, Timer, Hourglass, Calendar,
  Music, Drum, Guitar, Piano,
  Pill, Syringe, Bandage, Hospital,
  Microscope, Beaker, Atom, Magnet, Scale, Ruler, Calculator,
};


export const STORY_ICON_NAMES: string[] = [
  'Home', 'Flame', 'TreePine', 'Wind', 'Waves', 'Sparkles', 'MapPin', 'Mountain', 'Castle', 'Sword', 'Shield',
  'Star', 'Sun', 'Moon', 'Cloud', 'Zap', 'Heart', 'Eye', 'Diamond', 'Gem', 'Crown',
  'Key', 'Lock', 'Footprints', 'Compass', 'Telescope', 'BookOpen', 'Scroll', 'Feather', 'Wand2', 
  'Rabbit', 'Fish', 'Bird', 'Bug', 'Flower', 'Leaf', 'Snowflake',
  'Navigation', 'Route', 'Signpost', 'Milestone', 'Target', 'Locate',
  'Flower2', 'Cherry', 'CloudSnow', 'CloudRain', 'Rainbow', 'Sunrise', 'Sunset', 'Eclipse',
  'Snail', 'Turtle', 'Cat', 'Dog', 'MousePointer', 'PawPrint',
  'Shell', 'Axe', 'Hammer', 'Bolt', 'Power',
  'Building', 'Church', 'House', 'Warehouse', 'Factory', 'Tent', 'DoorOpen', 'DoorClosed',
  'Unlock', 'Box', 'Package', 'Gift', 'Coins',
  'Wrench', 'Pickaxe', 'Shovel', 'Anchor', 'Bell',
  'HeartHandshake', 'Smile', 'Frown', 'Angry',
  'Book', 'ScrollText', 'Map',
  'Watch', 'Clock', 'Timer', 'Hourglass', 'Calendar',
  'Music', 'Drum', 'Guitar', 'Piano',
  'Pill', 'Syringe', 'Bandage', 'Hospital',
  'Microscope', 'Beaker', 'Atom', 'Magnet', 'Scale', 'Ruler', 'Calculator',
]